stages:
  - lint
  - build
  - test

lintStage:
  stage: lint
  script:
    - sh ci/soanr_lint.sh

buildStage:
  stage: build
  before_script:
    - echo "start building"
  script:
    - make build_env  # ci test should use production server


testStage:
  stage: test
  script:
    - make citest
    - sh ci/coverage_report.sh
